course_name = 'CS101'

[lecturers]
[[lecturers.items]]
name = 'Test Teacher'

[[lecturers.items.reviews]]
content = 'Initial review'

[lecturers.items.reviews.author]
link = 'https://github.com/test'
name = 'test'

[[lecturers.items]]
name = 'New Teacher'

[[lecturers.items.reviews]]
content = 'Great course! Added via pr-server.'

[lecturers.items.reviews.author]
date = ''
link = 'https://github.com/test'
name = 'test'
